version: '3.8'
services:
  ap-screen_backend_1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:5000 
    volumes:
      - .:/opt/airflow/dags
    depends_on: 
      - ap-screen_db_1

  ap-screen_db_1:
    image: mysql:5.7.22
    restart: always
    environment: 
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306